12-Nov-2021 15:37:52 [main] ERROR flota.service.utils.MailOperations - com.sun.mail.util.MailConnectException: Couldn't connect to host, port: localhost, 25; timeout -1;
  nested exception is:
	java.net.ConnectException: Connection refused: connect
12-Nov-2021 15:37:52 [main] ERROR flota.service.utils.MapUtils - getDistantaTraseuCoordonate -> com.google.maps.errors.UnknownErrorException: An unexpected error occurred. Status: MAX_WAYPOINTS_EXCEEDED, Message: Too many waypoints in the request (36). The maximum allowed waypoints for this request is 25, plus the origin, and destination.
	at com.google.maps.errors.ApiException.from(ApiException.java:70)
	at com.google.maps.DirectionsApi$Response.getError(DirectionsApi.java:69)
	at com.google.maps.internal.OkHttpPendingResult.parseResponse(OkHttpPendingResult.java:236)
	at com.google.maps.internal.OkHttpPendingResult.await(OkHttpPendingResult.java:152)
	at com.google.maps.PendingResultBase.await(PendingResultBase.java:56)
	at flota.service.utils.MapUtils.getDistantaTraseuCoordonate(MapUtils.java:246)
	at flota.service.model.ServiceDelegatii.calculeazaKmTeoretici(ServiceDelegatii.java:82)
	at flota.service.model.ServiceDelegatii.calculeazaKmSfarsitLuna(ServiceDelegatii.java:63)
	at flota.service.test.TestClass.main(TestClass.java:45)

12-Nov-2021 15:41:21 [main] ERROR flota.service.utils.MailOperations - com.sun.mail.util.MailConnectException: Couldn't connect to host, port: localhost, 25; timeout -1;
  nested exception is:
	java.net.ConnectException: Connection refused: connect
12-Nov-2021 15:41:21 [main] ERROR flota.service.utils.MapUtils - getDistantaTraseuCoordonate -> com.google.maps.errors.UnknownErrorException: An unexpected error occurred. Status: MAX_WAYPOINTS_EXCEEDED, Message: Too many waypoints in the request (98). The maximum allowed waypoints for this request is 25, plus the origin, and destination.
	at com.google.maps.errors.ApiException.from(ApiException.java:70)
	at com.google.maps.DirectionsApi$Response.getError(DirectionsApi.java:69)
	at com.google.maps.internal.OkHttpPendingResult.parseResponse(OkHttpPendingResult.java:236)
	at com.google.maps.internal.OkHttpPendingResult.await(OkHttpPendingResult.java:152)
	at com.google.maps.PendingResultBase.await(PendingResultBase.java:56)
	at flota.service.utils.MapUtils.getDistantaTraseuCoordonate(MapUtils.java:246)
	at flota.service.model.ServiceDelegatii.calculeazaKmTeoretici(ServiceDelegatii.java:82)
	at flota.service.model.ServiceDelegatii.calculeazaKmSfarsitLuna(ServiceDelegatii.java:63)
	at flota.service.test.TestClass.main(TestClass.java:45)

12-Nov-2021 15:46:07 [main] ERROR flota.service.utils.MailOperations - com.sun.mail.util.MailConnectException: Couldn't connect to host, port: localhost, 25; timeout -1;
  nested exception is:
	java.net.ConnectException: Connection refused: connect
12-Nov-2021 15:46:07 [main] ERROR flota.service.utils.MapUtils - getDistantaTraseuCoordonate -> com.google.maps.errors.UnknownErrorException: An unexpected error occurred. Status: MAX_WAYPOINTS_EXCEEDED, Message: Too many waypoints in the request (31). The maximum allowed waypoints for this request is 25, plus the origin, and destination.
	at com.google.maps.errors.ApiException.from(ApiException.java:70)
	at com.google.maps.DirectionsApi$Response.getError(DirectionsApi.java:69)
	at com.google.maps.internal.OkHttpPendingResult.parseResponse(OkHttpPendingResult.java:236)
	at com.google.maps.internal.OkHttpPendingResult.await(OkHttpPendingResult.java:152)
	at com.google.maps.PendingResultBase.await(PendingResultBase.java:56)
	at flota.service.utils.MapUtils.getDistantaTraseuCoordonate(MapUtils.java:246)
	at flota.service.model.ServiceDelegatii.calculeazaKmTeoretici(ServiceDelegatii.java:82)
	at flota.service.model.ServiceDelegatii.calculeazaKmSfarsitLuna(ServiceDelegatii.java:63)
	at flota.service.test.TestClass.main(TestClass.java:45)

22-Feb-2022 16:10:40 [main] ERROR flota.service.model.OperatiiMasina - java.sql.SQLSyntaxErrorException: ORA-00904: "OLD_VCODE": identificator nevalid

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:447)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:396)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:951)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:513)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:227)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:531)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:208)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForDescribe(T4CPreparedStatement.java:886)
	at oracle.jdbc.driver.OracleStatement.executeMaybeDescribe(OracleStatement.java:1175)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1296)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3613)
	at oracle.jdbc.driver.OraclePreparedStatement.executeQuery(OraclePreparedStatement.java:3657)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeQuery(OraclePreparedStatementWrapper.java:1495)
	at flota.service.model.OperatiiMasina.getNrAutoCodGps(OperatiiMasina.java:231)
	at flota.service.test.TestJava.main(TestJava.java:23)

22-Feb-2022 16:10:42 [main] ERROR flota.service.utils.MailOperations - com.sun.mail.util.MailConnectException: Couldn't connect to host, port: localhost, 25; timeout -1;
  nested exception is:
	java.net.ConnectException: Connection refused: connect
22-Feb-2022 16:13:23 [main] ERROR flota.service.model.OperatiiMasina - java.sql.SQLException: Invalid column index
	at oracle.jdbc.driver.OraclePreparedStatement.setStringInternal(OraclePreparedStatement.java:5386)
	at oracle.jdbc.driver.OraclePreparedStatement.setString(OraclePreparedStatement.java:5374)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.setString(OraclePreparedStatementWrapper.java:282)
	at flota.service.model.OperatiiMasina.getNrAutoCodGps(OperatiiMasina.java:230)
	at flota.service.test.TestJava.main(TestJava.java:23)

22-Feb-2022 16:13:25 [main] ERROR flota.service.utils.MailOperations - com.sun.mail.util.MailConnectException: Couldn't connect to host, port: localhost, 25; timeout -1;
  nested exception is:
	java.net.ConnectException: Connection refused: connect
22-Feb-2022 16:14:24 [main] ERROR flota.service.model.OperatiiMasina - java.sql.SQLException: Invalid column index
	at oracle.jdbc.driver.OraclePreparedStatement.setStringInternal(OraclePreparedStatement.java:5386)
	at oracle.jdbc.driver.OraclePreparedStatement.setString(OraclePreparedStatement.java:5374)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.setString(OraclePreparedStatementWrapper.java:282)
	at flota.service.model.OperatiiMasina.getNrAutoCodGps(OperatiiMasina.java:230)
	at flota.service.test.TestJava.main(TestJava.java:23)

22-Feb-2022 16:14:27 [main] ERROR flota.service.utils.MailOperations - com.sun.mail.util.MailConnectException: Couldn't connect to host, port: localhost, 25; timeout -1;
  nested exception is:
	java.net.ConnectException: Connection refused: connect
18-May-2022 15:51:21 [main] ERROR flota.service.model.OperatiiAngajat - java.sql.SQLException: Invalid column index
	at oracle.jdbc.driver.OraclePreparedStatement.setStringInternal(OraclePreparedStatement.java:5386)
	at oracle.jdbc.driver.OraclePreparedStatement.setString(OraclePreparedStatement.java:5374)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.setString(OraclePreparedStatementWrapper.java:282)
	at flota.service.model.OperatiiAngajat.getAngajati(OperatiiAngajat.java:111)
	at flota.service.test.TestClass.main(TestClass.java:32)

18-May-2022 15:51:23 [main] ERROR flota.service.utils.MailOperations - com.sun.mail.util.MailConnectException: Couldn't connect to host, port: localhost, 25; timeout -1;
  nested exception is:
	java.net.ConnectException: Connection refused: connect
18-May-2022 16:04:46 [main] ERROR flota.service.model.OperatiiAngajat - java.sql.SQLException: Invalid column name
	at oracle.jdbc.driver.OracleStatement.getColumnIndex(OracleStatement.java:3724)
	at oracle.jdbc.driver.OracleResultSetImpl.findColumn(OracleResultSetImpl.java:2799)
	at oracle.jdbc.driver.ScrollableResultSet.findColumn(ScrollableResultSet.java:2068)
	at oracle.jdbc.driver.OracleResultSet.getString(OracleResultSet.java:498)
	at flota.service.model.OperatiiAngajat.getAngajati(OperatiiAngajat.java:134)
	at flota.service.test.TestClass.main(TestClass.java:32)

18-May-2022 16:04:48 [main] ERROR flota.service.utils.MailOperations - com.sun.mail.util.MailConnectException: Couldn't connect to host, port: localhost, 25; timeout -1;
  nested exception is:
	java.net.ConnectException: Connection refused: connect
18-Jul-2022 09:53:57 [main] ERROR flota.service.model.OperatiiDelegatii - java.sql.SQLException: Invalid column index
	at oracle.jdbc.driver.OraclePreparedStatement.setStringInternal(OraclePreparedStatement.java:5386)
	at oracle.jdbc.driver.OraclePreparedStatement.setString(OraclePreparedStatement.java:5374)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.setString(OraclePreparedStatementWrapper.java:282)
	at flota.service.model.OperatiiDelegatii.getDelegatiiAprobari(OperatiiDelegatii.java:160)
	at flota.service.test.TestClass.main(TestClass.java:42)

18-Jul-2022 09:53:59 [main] ERROR flota.service.utils.MailOperations - com.sun.mail.util.MailConnectException: Couldn't connect to host, port: localhost, 25; timeout -1;
  nested exception is:
	java.net.ConnectException: Connection refused: connect
